/* ACROW Factory 5 — production green + unified monthly-plan admin lock v13 */
(function(){
'use strict';
var STYLE_ID='acrow-production-green-v13';
function setupStyle(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent='input.actual-input.acrow-fixed{background:#b9f3d1!important;border:3px solid #159957!important;color:#063b22!important;box-shadow:none!important;} .machine-card.acrow-production-done{background:linear-gradient(135deg,#123d2b,#102d22)!important;border-color:#159957!important;box-shadow:0 0 0 2px rgba(21,153,87,.18),inset 0 0 18px rgba(21,153,87,.08)!important;} .machine-card.acrow-production-done .mc-name{color:#b9f3d1!important;}';document.head.appendChild(s);}
function disableGoogleTranslate(){try{document.documentElement.classList.add('notranslate');document.body.classList.add('notranslate');if(!document.querySelector('meta[name="google"]')){var m=document.createElement('meta');m.name='google';m.content='notranslate';document.head.appendChild(m);}}catch(e){}}
function paint(input){if(!input)return;var has=String(input.value||'').trim()!=='';input.classList.toggle('acrow-fixed',has);var card=input.closest('.machine-card');if(card)card.classList.toggle('acrow-production-done',has);}
function paintAll(){setupStyle();disableGoogleTranslate();document.querySelectorAll('input.actual-input').forEach(paint);}
function saveInput(input){try{var id=String(input.dataset.machine||'').trim();if(!id||typeof getRecord!=='function'||typeof dateInput==='undefined')return;var r=getRecord(dateInput.value,currentShift,id);r.actual=input.value===''?null:Number(input.value);r.productionFixed=String(input.value||'').trim()!=='';if(typeof saveStore==='function')saveStore();}catch(e){}}
document.addEventListener('input',function(e){var input=e.target&&e.target.closest?e.target.closest('input.actual-input'):null;if(!input)return;paint(input);saveInput(input);try{if(typeof updateSummaryOnly==='function')updateSummaryOnly();}catch(x){}try{if(typeof renderReport==='function')renderReport();}catch(x){}},true);
document.addEventListener('change',function(e){var input=e.target&&e.target.closest?e.target.closest('input.actual-input'):null;if(input){paint(input);saveInput(input);}},true);
var PASSWORD='5445';
var IDS=['planStatusBtn','maintenanceBtn','adminMenuBtn','jumpToAnalysisBtn'];
var TITLES={planStatusBtn:'الخطة الشهرية',maintenanceBtn:'الصيانة',adminMenuBtn:'صفحة التعديل',jumpToAnalysisBtn:'التقارير',textReportPrint:'طباعة التقارير',textReports:'التقارير'};
var pendingId=null,pendingEl=null,monthlyAdminPending=false;
function ensureLock(){if(document.getElementById('acrowLockOverlay'))return;var o=document.createElement('div');o.id='acrowLockOverlay';o.className='acrow-lock-overlay';o.style.display='none';o.innerHTML='<div class="acrow-lock-box" role="dialog" aria-modal="true"><h3 id="acrowLockTitle">صفحة التعديل</h3><div class="acrow-lock-sub">محمية بكلمة مرور — أدخل الرمز للدخول</div><input type="text" id="acrowLockInput" name="acrow_access_code" inputmode="numeric" pattern="[0-9]*" placeholder="كلمة المرور" autocomplete="new-password" autocapitalize="off" autocorrect="off" spellcheck="false" style="-webkit-text-security:disc;"><div id="acrowLockError" class="acrow-lock-error">كلمة المرور غلط</div><div class="acrow-lock-actions"><button type="button" id="acrowLockCancel">إلغاء</button><button type="button" id="acrowLockEnter" class="acrow-lock-enter">دخول</button></div></div>';document.body.appendChild(o);var input=o.querySelector('#acrowLockInput');o.querySelector('#acrowLockCancel').onclick=function(){closeLock();};o.querySelector('#acrowLockEnter').onclick=function(){unlock();};input.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();unlock();}if(e.key==='Escape'){e.preventDefault();closeLock();}});o.addEventListener('click',function(e){if(e.target===o)closeLock();});}
function closeLock(){var o=document.getElementById('acrowLockOverlay');if(o)o.style.display='none';pendingId=null;pendingEl=null;}
function showLock(id,el){ensureLock();pendingId=id;pendingEl=el||null;var o=document.getElementById('acrowLockOverlay');var t=document.getElementById('acrowLockTitle');var i=document.getElementById('acrowLockInput');var er=document.getElementById('acrowLockError');t.textContent=TITLES[id]||'الدخول';i.value='';er.style.display='none';o.style.display='flex';setTimeout(function(){i.focus();},60);}
function openMonthlyAdminLock(){var modal=document.getElementById('adminModal'),lock=document.getElementById('adminLockView'),settings=document.getElementById('adminSettingsView'),input=document.getElementById('adminPasswordInput'),err=document.getElementById('adminPasswordError');if(!modal||!lock||!input){showLock('planStatusBtn');return;}monthlyAdminPending=true;if(settings)settings.style.display='none';lock.style.display='';input.value='';if(err)err.style.display='none';modal.classList.add('open');setTimeout(function(){input.focus();},60);}
function closeMonthlyAdminLock(){var modal=document.getElementById('adminModal');monthlyAdminPending=false;if(modal)modal.classList.remove('open');}
function unlock(){var i=document.getElementById('acrowLockInput');if(!i)return;if(String(i.value)!==PASSWORD){document.getElementById('acrowLockError').style.display='block';i.value='';i.focus();return;}var id=pendingId,el=pendingEl;closeLock();if(id==='textReportPrint'||id==='textReports'){if(el){el.dataset.acrowUnlocked='1';el.click();setTimeout(function(){try{delete el.dataset.acrowUnlocked;}catch(e){}},300);}return;}openProtected(id);}
function openProtected(id){if(id==='planStatusBtn'){if(typeof window.openMonthlyPlan==='function'){window.openMonthlyPlan();return;}var b=document.getElementById('planStatusBtn');if(b){b.dataset.acrowUnlocked='1';b.click();setTimeout(function(){try{delete b.dataset.acrowUnlocked;}catch(e){}},300);}return;}if(id==='maintenanceBtn'&&typeof window.openMaintenanceView==='function'){window.openMaintenanceView();return;}if(id==='adminMenuBtn'&&typeof window.openAdminModal==='function'){window.openAdminModal();setTimeout(function(){var lock=document.getElementById('adminLockView'),settings=document.getElementById('adminSettingsView');if(lock&&settings){lock.style.display='none';settings.style.display='';}},0);return;}if(id==='jumpToAnalysisBtn'){var sec=document.getElementById('analysisSection');if(sec){sec.style.display='';sec.scrollIntoView({behavior:'smooth',block:'start'});}try{if(typeof renderReport==='function')renderReport();}catch(e){}}}
function installGuards(){ensureLock();IDS.forEach(function(id){var el=document.getElementById(id);if(!el||el.dataset.acrowGuard==='1')return;el.dataset.acrowGuard='1';el.onclick=function(e){if(e){e.preventDefault();e.stopPropagation();}if(id==='planStatusBtn'){openMonthlyAdminLock();}else{showLock(id);}return false;};});}
function blockMonthlyPointer(e){var el=e.target&&e.target.closest?e.target.closest('#planStatusBtn'):null;if(!el)return;if(el.closest('#adminModal')||el.closest('#acrowLockOverlay'))return;if(el.dataset.acrowUnlocked==='1'){delete el.dataset.acrowUnlocked;return;}e.preventDefault();e.stopImmediatePropagation();openMonthlyAdminLock();}
function captureGuard(e){var el=e.target&&e.target.closest?e.target.closest('#planStatusBtn,#maintenanceBtn,#adminMenuBtn,#jumpToAnalysisBtn'):null;if(el){if(el.closest('#acrowLockOverlay'))return;if(el.dataset.acrowUnlocked==='1'){delete el.dataset.acrowUnlocked;return;}e.preventDefault();e.stopImmediatePropagation();if(el.id==='planStatusBtn'){openMonthlyAdminLock();}else{showLock(el.id);}return;}var textEl=e.target&&e.target.closest?e.target.closest('button,a,[role="button"]'):null;if(!textEl||textEl.closest('#acrowLockOverlay'))return;if(textEl.dataset.acrowUnlocked==='1'){delete textEl.dataset.acrowUnlocked;return;}if(textEl.id&&IDS.indexOf(textEl.id)>=0)return;var text=(textEl.textContent||'').replace(/\s+/g,' ').trim();if(text==='طباعة التقارير'){e.preventDefault();e.stopImmediatePropagation();showLock('textReportPrint',textEl);return;}if(text==='التقارير'){e.preventDefault();e.stopImmediatePropagation();showLock('textReports',textEl);return;}}
document.addEventListener('pointerdown',blockMonthlyPointer,true);
document.addEventListener('touchstart',blockMonthlyPointer,true);
document.addEventListener('click',function(e){if(!monthlyAdminPending)return;var btn=e.target&&e.target.closest?e.target.closest('#adminUnlockBtn,#adminCancelBtn'):null;if(!btn)return;e.preventDefault();e.stopImmediatePropagation();var modal=document.getElementById('adminModal'),input=document.getElementById('adminPasswordInput'),err=document.getElementById('adminPasswordError');if(btn.id==='adminCancelBtn'){closeMonthlyAdminLock();return;}if(String(input&&input.value||'')!==PASSWORD){if(err)err.style.display='block';if(input){input.value='';input.focus();}return;}monthlyAdminPending=false;if(modal)modal.classList.remove('open');if(typeof window.openMonthlyPlan==='function'){setTimeout(function(){window.openMonthlyPlan();},0);}},true);
function start(){setupStyle();disableGoogleTranslate();paintAll();installGuards();document.addEventListener('click',captureGuard,true);var o=new MutationObserver(function(){paintAll();installGuards();});o.observe(document.body,{childList:true,subtree:true});setTimeout(installGuards,300);setTimeout(installGuards,1000);setTimeout(installGuards,2000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
